language: go
sudo: false
os:
    - osx

branches:
    only:
        - master

go:
    - 1.15.x

env:
    global:
        - GO111MODULE=on

before_install:
    - go get -v golang.org/x/lint/golint

before_script:
    - go vet ./...
    - go test -v ./...

script:
    - go build -ldflags "-s -w"

before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: "$GITHUB_TOKEN"
  file: blueprint
  skip_cleanup: true
  # Only build binaries for tagged commits
  tags: true
  condition: $LATEST = true
