language: go

os:
  - windows
  - linux
  - osx

branches:
  only:
    - master
    - develop

go:
  - 1.15.x

env:
  global:
    - GO111MODULE=on

before_install:
  - go get -v golang.org/x/lint/golint

before_script:
  - go vet ./...
  - go test -v ./...

script:
  - go build

# before_deploy:
#   - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#   - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: blueprint
  skip_cleanup: true
